"""Stable identity for the generated public Gateway client contract."""

from __future__ import annotations

CONTRACT_SCHEMA_VERSION = 1
CONTRACT_GENERATED_FROM = "gateway"

# Generated by scripts/generate_client_contracts.py. Do not edit.
# Runtime handshakes import this module without scanning contract artifacts.
CLIENT_CONTRACT_DIGEST = "sha256:9819d28398fd37609c8c86ae9b5bbf8133d122ae07f06b75817a4d5b3c30a79e"

__all__ = [
    "CLIENT_CONTRACT_DIGEST",
    "CONTRACT_GENERATED_FROM",
    "CONTRACT_SCHEMA_VERSION",
]
