"""Stable identity for the generated public Gateway client contract."""

from __future__ import annotations

CONTRACT_SCHEMA_VERSION = 1
CONTRACT_GENERATED_FROM = "gateway"

# Generated by scripts/generate_client_contracts.py. Do not edit.
# Runtime handshakes import this module without scanning contract artifacts.
CLIENT_CONTRACT_DIGEST = "sha256:5f5a5ab81b3b7ec23ca6dc1e30d520bfe5b6eb214d11f39c15bd741e77b0cf0a"

__all__ = [
    "CLIENT_CONTRACT_DIGEST",
    "CONTRACT_GENERATED_FROM",
    "CONTRACT_SCHEMA_VERSION",
]
