"""Stable identity for the generated public Gateway client contract."""

from __future__ import annotations

CONTRACT_SCHEMA_VERSION = 1
CONTRACT_GENERATED_FROM = "gateway"

# Generated by scripts/generate_client_contracts.py. Do not edit.
# Runtime handshakes import this module without scanning contract artifacts.
CLIENT_CONTRACT_DIGEST = "sha256:161c755919f411e26d22d56253305a7f873700248b30db892dce433263c00f33"

__all__ = [
    "CLIENT_CONTRACT_DIGEST",
    "CONTRACT_GENERATED_FROM",
    "CONTRACT_SCHEMA_VERSION",
]
