"""Implementation-free client protocol owned by the shared contract layer."""

from opensquilla.contracts.client.envelope import (
    EventFrame,
    PingFrame,
    PongFrame,
    ReqFrame,
    ResFrame,
    StateVersion,
)
from opensquilla.contracts.client.errors import (
    DECLARED_ERROR_CODES,
    ERROR_AGENT_TIMEOUT,
    ERROR_APPROVAL_NOT_FOUND,
    ERROR_INVALID_REQUEST,
    ERROR_METHOD_NOT_FOUND,
    ERROR_NOT_FOUND,
    ERROR_NOT_LINKED,
    ERROR_NOT_PAIRED,
    ERROR_UNAUTHORIZED,
    ERROR_UNAVAILABLE,
    ErrorShape,
)
from opensquilla.contracts.client.events import DECLARED_EVENTS, EVENT_PATTERNS
from opensquilla.contracts.client.hello import (
    DEDUPE_MAX_ENTRIES,
    DEDUPE_TTL_MS,
    HEALTH_REFRESH_INTERVAL_MS,
    MAX_BUFFERED_BYTES,
    MAX_PAYLOAD_BYTES,
    MAX_PREAUTH_PAYLOAD_BYTES,
    PREAUTH_TIMEOUT_MS,
    PROTOCOL_VERSION,
    TICK_INTERVAL_MS,
    WS_CLOSE_SERVICE_RESTART,
    ClientInfo,
    ConnectParams,
    ContractInfo,
    FeaturesInfo,
    HelloOk,
    PolicyInfo,
    ProtocolRangeInfo,
    RuntimeInfo,
    ServerInfo,
    SnapshotInfo,
)

__all__ = [
    "DECLARED_ERROR_CODES",
    "DECLARED_EVENTS",
    "DEDUPE_MAX_ENTRIES",
    "DEDUPE_TTL_MS",
    "ERROR_AGENT_TIMEOUT",
    "ERROR_APPROVAL_NOT_FOUND",
    "ERROR_INVALID_REQUEST",
    "ERROR_METHOD_NOT_FOUND",
    "ERROR_NOT_FOUND",
    "ERROR_NOT_LINKED",
    "ERROR_NOT_PAIRED",
    "ERROR_UNAUTHORIZED",
    "ERROR_UNAVAILABLE",
    "EVENT_PATTERNS",
    "HEALTH_REFRESH_INTERVAL_MS",
    "MAX_BUFFERED_BYTES",
    "MAX_PAYLOAD_BYTES",
    "MAX_PREAUTH_PAYLOAD_BYTES",
    "PREAUTH_TIMEOUT_MS",
    "PROTOCOL_VERSION",
    "TICK_INTERVAL_MS",
    "WS_CLOSE_SERVICE_RESTART",
    "ClientInfo",
    "ConnectParams",
    "ContractInfo",
    "ErrorShape",
    "EventFrame",
    "FeaturesInfo",
    "HelloOk",
    "PingFrame",
    "PolicyInfo",
    "PongFrame",
    "ProtocolRangeInfo",
    "ReqFrame",
    "ResFrame",
    "RuntimeInfo",
    "ServerInfo",
    "SnapshotInfo",
    "StateVersion",
]
