"""Determinism and coverage tests for the generated TypeScript client SDK."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from scripts.generate_client_contracts import (
    check_sdk,
    main,
    render_contract_identity,
    render_sdk_artifacts,
    write_sdk,
)


def test_generated_sdk_is_byte_identical_across_repeated_runs(tmp_path: Path) -> None:
    sdk_root = tmp_path / "sdk"

    first = write_sdk(sdk_root)
    generated = (sdk_root / "src" / "generated.ts").read_bytes()
    coverage = (sdk_root / "contract-coverage.json").read_bytes()
    second = write_sdk(sdk_root)

    assert first.ok
    assert second.ok
    assert check_sdk(sdk_root).ok
    assert (sdk_root / "src" / "generated.ts").read_bytes() == generated
    assert (sdk_root / "contract-coverage.json").read_bytes() == coverage


def test_check_detects_missing_and_changed_sdk_files_without_repairing(
    tmp_path: Path,
) -> None:
    sdk_root = tmp_path / "sdk"
    assert write_sdk(sdk_root).ok
    generated = sdk_root / "src" / "generated.ts"
    coverage = sdk_root / "contract-coverage.json"
    generated.write_text("// manual edit\n", encoding="utf-8")
    coverage.unlink()

    result = check_sdk(sdk_root)

    assert [path.as_posix() for path in result.changed] == ["src/generated.ts"]
    assert [path.as_posix() for path in result.missing] == ["contract-coverage.json"]
    assert generated.read_text(encoding="utf-8") == "// manual edit\n"
    assert not coverage.exists()


def test_generated_types_preserve_wire_names_optional_null_and_unions() -> None:
    generated = render_sdk_artifacts()
    source = generated[next(path for path in generated if path.name == "generated.ts")].decode()

    assert 'type: "req";' in source
    assert "id?: string | null;" in source
    assert "contract?: ContractInfo | null;" in source
    assert "minProtocol?: Integer;" in source
    assert "state_version?: StateVersion | null;" in source
    assert "export type Frame = ReqFrame | ResFrame | EventFrame" in source
    assert "export type ConnectRequest = {" in source
    assert "method: \"connect\";" in source


def test_generated_catalog_and_coverage_are_machine_readable() -> None:
    generated = render_sdk_artifacts()
    source = generated[next(path for path in generated if path.name == "generated.ts")].decode()
    coverage_path = next(path for path in generated if path.name == "contract-coverage.json")
    coverage = json.loads(generated[coverage_path])

    assert '"agent": "operator.write"' in source
    assert '"connect.challenge"' in source
    assert '"session.event.*"' in source
    assert coverage["coverage"]["transportEnvelopes"] == "complete"
    assert coverage["coverage"]["rpcCatalog"]["totalMethods"] >= 200
    assert coverage["coverage"]["rpcCatalog"]["payloadContracts"] == "deferred-by-domain"
    assert coverage["coverage"]["events"]["payloadContracts"] == "deferred-by-domain"


def test_runtime_identity_is_deterministic_and_import_only() -> None:
    artifacts = render_sdk_artifacts()
    coverage_path = next(path for path in artifacts if path.name == "contract-coverage.json")
    coverage = json.loads(artifacts[coverage_path])
    manifest = {
        "digest": coverage["contractDigest"],
        "schemaVersion": coverage["schemaVersion"],
        "generatedFrom": "gateway",
    }

    first = render_contract_identity(manifest)
    second = render_contract_identity(manifest)

    assert first == second
    assert coverage["contractDigest"].encode() in first
    assert b"Path(" not in first
    assert b"Generated by scripts/generate_client_contracts.py" in first


def test_main_check_reports_drift_across_contract_and_sdk(tmp_path: Path) -> None:
    contract_dir = tmp_path / "contract"
    sdk_root = tmp_path / "sdk"
    identity_path = tmp_path / "contract_identity.py"

    common = [
        "--contract-dir",
        str(contract_dir),
        "--sdk-root",
        str(sdk_root),
        "--identity-path",
        str(identity_path),
    ]
    assert main(common) == 0
    assert (
        main(
            [
                "--check",
                *common,
            ]
        )
        == 0
    )
    (sdk_root / "src" / "generated.ts").write_text("// drift\n", encoding="utf-8")
    assert (
        main(
            [
                "--check",
                *common,
            ]
        )
        == 1
    )


def test_generator_is_directly_executable_from_repository_root(tmp_path: Path) -> None:
    contract_dir = tmp_path / "contract"
    sdk_root = tmp_path / "sdk"
    identity_path = tmp_path / "contract_identity.py"
    assert (
        main(
            [
                "--contract-dir",
                str(contract_dir),
                "--sdk-root",
                str(sdk_root),
                "--identity-path",
                str(identity_path),
            ]
        )
        == 0
    )

    result = subprocess.run(
        [
            sys.executable,
            "scripts/generate_client_contracts.py",
            "--check",
            "--contract-dir",
            str(contract_dir),
            "--sdk-root",
            str(sdk_root),
            "--identity-path",
            str(identity_path),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "matches generated sources" in result.stdout
