/* eslint-disable */
// Generated by scripts/generate_client_contracts.py. Do not edit.
// Source contract: sha256:9819d28398fd37609c8c86ae9b5bbf8133d122ae07f06b75817a4d5b3c30a79e

export const CLIENT_CONTRACT_SCHEMA_VERSION = 1 as const;
export const CLIENT_CONTRACT_DIGEST = "sha256:9819d28398fd37609c8c86ae9b5bbf8133d122ae07f06b75817a4d5b3c30a79e" as const;

/** JSON Schema integer. Validate with Number.isInteger at runtime. */
export type Integer = number;

export interface ErrorShape {
  accepted?: boolean | null;
  code: string;
  details?: unknown | null;
  message: string;
  retry_after_ms?: Integer | null;
  retryable?: boolean | null;
}

export interface StateVersion {
  health?: Integer;
  presence?: Integer;
}

export interface ReqFrame {
  id: string;
  method: string;
  params?: unknown | null;
  type: "req";
}

export interface ResFrame {
  error?: ErrorShape | null;
  id: string;
  ok: boolean;
  payload?: unknown | null;
  type: "res";
}

export interface EventFrame {
  event: string;
  meta?: Record<string, unknown> | null;
  payload?: unknown | null;
  seq?: Integer | null;
  state_version?: StateVersion | null;
  type: "event";
}

export interface PingFrame {
  type: "ping";
}

export interface PongFrame {
  type: "pong";
}

export interface ServerInfo {
  conn_id: string;
  version: string;
}

export interface FeaturesInfo {
  events: Array<string>;
  methods: Array<string>;
}

export interface SnapshotInfo {
  auth_mode?: string | null;
  config_path?: string | null;
  health?: unknown;
  presence?: Array<unknown>;
  state_dir?: string | null;
  state_version?: StateVersion;
  uptime_ms?: Integer;
}

export interface PolicyInfo {
  agent_stream_heartbeat_interval_ms?: Integer;
  agent_stream_idle_timeout_ms?: Integer;
  client_ws_keepalive_timeout_ms?: Integer;
  concurrent_history_reads?: boolean;
  max_buffered_bytes?: Integer;
  max_payload?: Integer;
  tick_interval_ms?: Integer;
  webui_stream_idle_grace_ms?: Integer;
}

export interface ContractInfo {
  digest: string;
  generatedFrom: string;
  schemaVersion: Integer;
}

export interface RuntimeInfo {
  arch: string;
  buildCommit?: string | null;
  coreVersion: string;
  platform: string;
}

export interface ProtocolRangeInfo {
  max: Integer;
  min: Integer;
}

export interface ConnectParams {
  auth?: Record<string, unknown>;
  caps?: unknown | null;
  client?: unknown | null;
  commands?: unknown | null;
  locale?: unknown | null;
  maxProtocol?: Integer;
  minProtocol?: Integer;
  path_env?: unknown | null;
  permissions?: unknown | null;
  role?: string;
  scopes?: unknown | null;
  user_agent?: unknown | null;
  [key: string]: unknown;
}

export interface HelloOk {
  auth?: Record<string, unknown> | null;
  capabilities?: Array<string> | null;
  contract?: ContractInfo | null;
  extensions?: Array<string> | null;
  features: FeaturesInfo;
  id?: string | null;
  policy: PolicyInfo;
  protocol: Integer;
  protocolRange?: ProtocolRangeInfo | null;
  runtime?: RuntimeInfo | null;
  server: ServerInfo;
  snapshot: SnapshotInfo;
  type: "hello-ok";
}

export type ClientFrame = ReqFrame | PingFrame | PongFrame;

export type ServerFrame = ResFrame | EventFrame | HelloOk | PingFrame | PongFrame;

export type Frame = ReqFrame | ResFrame | EventFrame | HelloOk | PingFrame | PongFrame;

export type ConnectRequest = {
  id: string;
  method: "connect";
  params: {
    auth?: Record<string, unknown>;
    client?: Record<string, unknown>;
    maxProtocol?: Integer;
    minProtocol?: Integer;
    role?: string;
    scopes?: Array<string>;
    [key: string]: unknown;
  };
  type: "req";
  [key: string]: unknown;
};

export const DECLARED_ERROR_CODES = [
  "AGENT_TIMEOUT",
  "APPROVAL_NOT_FOUND",
  "INVALID_REQUEST",
  "METHOD_NOT_FOUND",
  "NOT_FOUND",
  "NOT_LINKED",
  "NOT_PAIRED",
  "UNAUTHORIZED",
  "UNAVAILABLE",
] as const;

export type DeclaredErrorCode = (typeof DECLARED_ERROR_CODES)[number];

export const RPC_METHOD_SCOPES = {
  "agent": "operator.write",
  "agent.identity.get": "operator.read",
  "agent.wait": "operator.write",
  "agents.create": "operator.admin",
  "agents.delete": "operator.admin",
  "agents.files.get": "operator.read",
  "agents.files.list": "operator.read",
  "agents.files.set": "operator.admin",
  "agents.list": "operator.read",
  "agents.update": "operator.admin",
  "channels.admin.set": "operator.pairing",
  "channels.get": "operator.admin",
  "channels.logout": "operator.admin",
  "channels.pairing.approve": "operator.pairing",
  "channels.pairing.revoke": "operator.pairing",
  "channels.pairings": "operator.pairing",
  "channels.probe": "operator.admin",
  "channels.restart": "operator.admin",
  "channels.status": "operator.read",
  "chat.abort": "operator.write",
  "chat.clarify_submit": "operator.write",
  "chat.history": "operator.read",
  "chat.inject": "operator.admin",
  "chat.send": "operator.write",
  "commands.list_for_surface": "operator.read",
  "config.apply": "operator.admin",
  "config.effective": "operator.read",
  "config.get": "operator.read",
  "config.patch": "operator.admin",
  "config.patch.safe": "operator.write",
  "config.reload": "operator.admin",
  "config.schema": "operator.admin",
  "config.schema.lookup": "operator.read",
  "config.set": "operator.admin",
  "cron.add": "operator.admin",
  "cron.create": "operator.admin",
  "cron.list": "operator.read",
  "cron.remove": "operator.admin",
  "cron.run": "operator.admin",
  "cron.runs": "operator.read",
  "cron.status": "operator.read",
  "cron.subscribe": "operator.read",
  "cron.unsubscribe": "operator.read",
  "cron.update": "operator.admin",
  "diagnostics.set": "operator.admin",
  "diagnostics.status": "operator.read",
  "doctor.memory.status": "operator.read",
  "doctor.status": "operator.read",
  "exec.approval.extend": "operator.approvals",
  "exec.approval.forget": "operator.approvals",
  "exec.approval.request": "operator.approvals",
  "exec.approval.resolve": "operator.approvals",
  "exec.approval.snapshot": "operator.approvals",
  "exec.approval.status": "operator.approvals",
  "exec.approval.waitDecision": "operator.approvals",
  "exec.approvals.get": "operator.approvals",
  "exec.approvals.node.get": "operator.admin",
  "exec.approvals.node.set": "operator.admin",
  "exec.approvals.set": "operator.approvals",
  "exec.proposals.accept": "operator.admin",
  "exec.proposals.auto_enabled.disable": "operator.admin",
  "exec.proposals.auto_enabled.list": "operator.proposals",
  "exec.proposals.list": "operator.proposals",
  "exec.proposals.pending_count": "operator.proposals",
  "exec.proposals.reject": "operator.admin",
  "exec.proposals.settings.get": "operator.proposals",
  "exec.proposals.settings.set": "operator.admin",
  "exec.proposals.show": "operator.proposals",
  "gateway.identity.get": "operator.read",
  "health": "operator.read",
  "last-heartbeat": "operator.read",
  "logs.status": "operator.read",
  "logs.tail": "operator.read",
  "logs.trace": "operator.read",
  "memory.import.apply": "operator.admin",
  "memory.import.cancel": "operator.admin",
  "memory.import.discard": "operator.admin",
  "memory.import.info": "operator.read",
  "memory.import.preview": "operator.admin",
  "memory.import.retry": "operator.admin",
  "memory.import.start": "operator.admin",
  "memory.import.status": "operator.admin",
  "memory.import.undo": "operator.admin",
  "memory.index": "operator.admin",
  "memory.list": "operator.read",
  "memory.raw_fallbacks.list": "operator.admin",
  "memory.raw_fallbacks.show": "operator.admin",
  "memory.repair.list": "operator.admin",
  "memory.repair.run": "operator.admin",
  "memory.repair.show": "operator.admin",
  "memory.search": "operator.read",
  "memory.show": "operator.read",
  "meta.list": "operator.read",
  "meta.run": "operator.write",
  "meta.runs.confirm_preflight": "operator.admin",
  "meta.runs.cost": "operator.read",
  "meta.runs.diff": "operator.admin",
  "meta.runs.draft": "operator.admin",
  "meta.runs.eval_baseline": "operator.admin",
  "meta.runs.failures": "operator.read",
  "meta.runs.list": "operator.read",
  "meta.runs.replay": "operator.admin",
  "meta.runs.show": "operator.admin",
  "meta.runs.validate": "operator.admin",
  "migration.sources.list": "operator.admin",
  "migration.sources.preview": "operator.admin",
  "models.list": "operator.read",
  "models.routing.get": "operator.read",
  "models.routing.set": "operator.write",
  "onboarding.audio.configure": "operator.admin",
  "onboarding.catalog": "operator.read",
  "onboarding.channel.disable": "operator.admin",
  "onboarding.channel.enable": "operator.admin",
  "onboarding.channel.probe": "operator.admin",
  "onboarding.channel.remove": "operator.admin",
  "onboarding.channel.upsert": "operator.admin",
  "onboarding.ensemble.configure": "operator.admin",
  "onboarding.imageGeneration.configure": "operator.admin",
  "onboarding.llmProfile.activate": "operator.admin",
  "onboarding.llmProfile.active.remove": "operator.admin",
  "onboarding.llmProfile.credential.clear": "operator.admin",
  "onboarding.llmProfile.draft.models.discover": "operator.admin",
  "onboarding.llmProfile.draft.probe": "operator.admin",
  "onboarding.llmProfile.models.discover": "operator.admin",
  "onboarding.llmProfile.probe": "operator.admin",
  "onboarding.llmProfile.remove": "operator.admin",
  "onboarding.llmProfile.upsert": "operator.admin",
  "onboarding.memory_embedding.configure": "operator.admin",
  "onboarding.models.discover": "operator.admin",
  "onboarding.provider.configure": "operator.admin",
  "onboarding.provider.credential.clear": "operator.admin",
  "onboarding.provider.credential.reveal": "operator.admin",
  "onboarding.provider.probe": "operator.admin",
  "onboarding.router.catalog": "operator.read",
  "onboarding.router.configure": "operator.admin",
  "onboarding.search.configure": "operator.admin",
  "onboarding.status": "operator.read",
  "plans.cancelRun": "operator.write",
  "plans.capabilities": "operator.read",
  "plans.implement": "operator.write",
  "plans.revise": "operator.write",
  "plans.setMode": "operator.write",
  "plugin.approval.extend": "operator.approvals",
  "plugin.approval.request": "operator.approvals",
  "plugin.approval.resolve": "operator.approvals",
  "plugin.approval.status": "operator.approvals",
  "plugin.approval.waitDecision": "operator.approvals",
  "providers.status": "operator.read",
  "router.decisions.list": "operator.read",
  "router.feedback.submit": "operator.write",
  "router.selflearning.status": "operator.read",
  "routing.hold.clear": "operator.admin",
  "routing.hold.get": "operator.read",
  "routing.hold.set": "operator.admin",
  "sandbox.bundle.disable": "operator.write",
  "sandbox.bundle.enable": "operator.write",
  "sandbox.domain.add": "operator.write",
  "sandbox.domain.remove": "operator.write",
  "sandbox.explain": "operator.read",
  "sandbox.mount.add": "operator.write",
  "sandbox.mount.remove": "operator.write",
  "sandbox.path.create-directory": "operator.write",
  "sandbox.path.list": "operator.read",
  "sandbox.path.pick": "operator.write",
  "sandbox.resume": "operator.write",
  "sandbox.run_context.get": "operator.read",
  "sandbox.run_context.set": "operator.write",
  "sandbox.run_mode.preference.get": "operator.read",
  "sandbox.run_mode.preference.set": "operator.write",
  "sandbox.setup.ensure": "operator.write",
  "sandbox.setup.status": "operator.read",
  "sandbox.status": "operator.read",
  "sandbox.workspace.set": "operator.write",
  "search.query": "operator.write",
  "search.status": "operator.read",
  "secrets.reload": "operator.admin",
  "secrets.resolve": "operator.admin",
  "send": "operator.write",
  "sessions.abort": "operator.write",
  "sessions.bootstrap": "operator.read",
  "sessions.compact": "operator.write",
  "sessions.contextCompact": "operator.write",
  "sessions.create": "operator.write",
  "sessions.delete": "operator.write",
  "sessions.fork": "operator.write",
  "sessions.get": "operator.read",
  "sessions.list": "operator.read",
  "sessions.messages.hydrate": "operator.read",
  "sessions.messages.snapshot": "operator.read",
  "sessions.messages.subscribe": "operator.read",
  "sessions.messages.unsubscribe": "operator.read",
  "sessions.patch": "operator.admin",
  "sessions.preview": "operator.read",
  "sessions.reset": "operator.write",
  "sessions.resolve": "operator.read",
  "sessions.search": "operator.read",
  "sessions.send": "operator.write",
  "sessions.steer": "operator.write",
  "sessions.steer.v2": "operator.write",
  "sessions.subscribe": "operator.read",
  "sessions.truncate": "operator.write",
  "sessions.unsubscribe": "operator.read",
  "set-heartbeats": "operator.admin",
  "skills.bins": "node",
  "skills.deps.install": "operator.admin",
  "skills.get": "operator.read",
  "skills.install": "operator.admin",
  "skills.list": "operator.read",
  "skills.reload": "operator.admin",
  "skills.search": "operator.read",
  "skills.status": "operator.read",
  "skills.uninstall": "operator.admin",
  "skills.update": "operator.admin",
  "status": "operator.read",
  "system-event": "operator.admin",
  "system-presence": "operator.read",
  "tools.catalog": "operator.read",
  "tools.effective": "operator.read",
  "tools.search_provider": "operator.read",
  "usage.cost": "operator.read",
  "usage.query": "operator.read",
  "usage.status": "operator.read",
  "wake": "operator.write",
  "wizard.cancel": "operator.admin",
  "wizard.next": "operator.admin",
  "wizard.start": "operator.admin",
  "wizard.status": "operator.admin",
  "workspaces.history.delete": "operator.write",
  "workspaces.list": "operator.read",
  "workspaces.open": "operator.write",
  "workspaces.pin": "operator.write",
  "workspaces.remove": "operator.write",
  "workspaces.update": "operator.write",
} as const;

export type RpcMethod = keyof typeof RPC_METHOD_SCOPES;
export type RpcScope = (typeof RPC_METHOD_SCOPES)[RpcMethod];

export const DECLARED_EVENTS = [
  "connect.challenge",
  "agent",
  "session.message",
  "sessions.changed",
  "presence",
  "tick",
  "shutdown",
  "health",
  "heartbeat",
  "cron",
] as const;

export const OBSERVED_CLIENT_EVENTS = [
  "channel.status",
  "collaboration_mode",
  "cron.run.finished",
  "exec.approval.requested",
  "exec.approval.resolved",
  "exec.approval.updated",
  "models.routing.changed",
  "plan_revision",
  "plan_run",
  "plugin.approval.requested",
  "plugin.approval.resolved",
  "plugin.approval.updated",
  "sandbox.run_mode.preference.changed",
  "session.epoch_changed",
  "session.event.artifact",
  "session.event.collaboration_mode",
  "session.event.compaction",
  "session.event.cron_result",
  "session.event.ensemble_progress",
  "session.event.input_disposition",
  "session.event.meta_preflight",
  "session.event.meta_run_announced",
  "session.event.meta_run_completed",
  "session.event.meta_step_state",
  "session.event.plan_revision",
  "session.event.plan_run",
  "session.event.router_control_replay",
  "session.event.router_decision",
  "session.event.run_heartbeat",
  "session.event.state_change",
  "session.event.subagent_completion",
  "session.event.task_group.done",
  "session.event.task_group.failed",
  "session.event.task_group.synthesizing",
  "session.event.task_group.waiting",
  "session.event.text_delta",
  "session.event.tool_result",
  "session.event.tool_use_delta",
  "session.event.tool_use_start",
  "session.event.warning",
  "sessions.changed",
  "task.queued",
  "task.running",
] as const;

export const EVENT_PATTERNS = [
  "session.event.*",
  "task.*",
] as const;

export type DeclaredEvent = (typeof DECLARED_EVENTS)[number];
export type ObservedClientEvent = (typeof OBSERVED_CLIENT_EVENTS)[number];
export type EventPattern = (typeof EVENT_PATTERNS)[number];
export type KnownEvent = DeclaredEvent | ObservedClientEvent;
