"""Generate or verify the public TypeScript client contract and SDK catalogs."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from tempfile import NamedTemporaryFile
from typing import Any

from opensquilla.gateway.client_contract import render_contract_artifacts

if __package__:
    from scripts.export_gateway_client_contract import (
        DEFAULT_OUTPUT_DIR,
        check_contract,
        write_contract,
    )
else:
    from export_gateway_client_contract import (  # type: ignore[import-not-found]
        DEFAULT_OUTPUT_DIR,
        check_contract,
        write_contract,
    )

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SDK_ROOT = REPOSITORY_ROOT / "packages" / "client-sdk"
DEFAULT_IDENTITY_PATH = (
    REPOSITORY_ROOT / "src" / "opensquilla" / "gateway" / "contract_identity.py"
)
GENERATED_SDK_PATHS = (
    PurePosixPath("contract-coverage.json"),
    PurePosixPath("src/generated.ts"),
)

_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


@dataclass(frozen=True, slots=True)
class GeneratedCheckResult:
    """Byte-level drift result for generated SDK files."""

    changed: tuple[PurePosixPath, ...] = ()
    missing: tuple[PurePosixPath, ...] = ()

    @property
    def ok(self) -> bool:
        return not (self.changed or self.missing)


def _json_bytes(payload: Any) -> bytes:
    return (json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode()


def render_contract_identity(manifest: Mapping[str, Any]) -> bytes:
    """Render the import-only runtime identity advertised during Hello."""

    digest = manifest.get("digest")
    schema_version = manifest.get("schemaVersion")
    generated_from = manifest.get("generatedFrom")
    if not isinstance(digest, str) or not digest.startswith("sha256:"):
        raise ValueError("contract manifest is missing a sha256 digest")
    if not isinstance(schema_version, int):
        raise ValueError("contract manifest is missing an integer schemaVersion")
    if not isinstance(generated_from, str):
        raise ValueError("contract manifest is missing generatedFrom")
    return (
        '"""Stable identity for the generated public Gateway client contract."""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        f"CONTRACT_SCHEMA_VERSION = {schema_version}\n"
        f'CONTRACT_GENERATED_FROM = "{generated_from}"\n'
        "\n"
        "# Generated by scripts/generate_client_contracts.py. Do not edit.\n"
        "# Runtime handshakes import this module without scanning contract artifacts.\n"
        f'CLIENT_CONTRACT_DIGEST = "{digest}"\n'
        "\n"
        "__all__ = [\n"
        '    "CLIENT_CONTRACT_DIGEST",\n'
        '    "CONTRACT_GENERATED_FROM",\n'
        '    "CONTRACT_SCHEMA_VERSION",\n'
        "]\n"
    ).encode()


def _json_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _property_name(name: str) -> str:
    return name if _IDENTIFIER_PATTERN.fullmatch(name) else json.dumps(name)


def _unique(items: Sequence[str]) -> list[str]:
    return list(dict.fromkeys(items))


def _ts_type(schema: Mapping[str, Any], *, indent: int = 0) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", 1)[-1]
    if "const" in schema:
        return _json_literal(schema["const"])
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        return " | ".join(_json_literal(value) for value in enum)

    variants = schema.get("anyOf")
    if not isinstance(variants, list):
        variants = schema.get("oneOf")
    if isinstance(variants, list):
        rendered = _unique(
            [
                _ts_type(variant, indent=indent)
                for variant in variants
                if isinstance(variant, Mapping)
            ]
        )
        return " | ".join(rendered) if rendered else "unknown"

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _unique([_ts_type({"type": item}, indent=indent) for item in schema_type])
        )
    if schema_type == "string":
        return "string"
    if schema_type == "integer":
        return "Integer"
    if schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        items = schema.get("items")
        item_type = _ts_type(items, indent=indent) if isinstance(items, Mapping) else "unknown"
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties")
        additional = schema.get("additionalProperties")
        if not isinstance(properties, Mapping):
            if isinstance(additional, Mapping):
                return f"Record<string, {_ts_type(additional, indent=indent)}>"
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        prefix = " " * indent
        child_prefix = " " * (indent + 2)
        lines = ["{"]
        for raw_name in sorted(properties):
            property_schema = properties[raw_name]
            if not isinstance(raw_name, str) or not isinstance(property_schema, Mapping):
                continue
            optional = "" if raw_name in required else "?"
            lines.append(
                f"{child_prefix}{_property_name(raw_name)}{optional}: "
                f"{_ts_type(property_schema, indent=indent + 2)};"
            )
        if additional is True or isinstance(additional, Mapping):
            value_type = (
                _ts_type(additional, indent=indent + 2)
                if isinstance(additional, Mapping)
                else "unknown"
            )
            lines.append(f"{child_prefix}[key: string]: {value_type};")
        lines.append(f"{prefix}}}")
        return "\n".join(lines)
    return "unknown"


def _render_definition(name: str, schema: Mapping[str, Any]) -> list[str]:
    if schema.get("type") == "object" or "properties" in schema:
        rendered = _ts_type(schema)
        return [f"export interface {name} {rendered}", ""]
    return [f"export type {name} = {_ts_type(schema)};", ""]


def _render_const_array(name: str, values: Sequence[str]) -> list[str]:
    lines = [f"export const {name} = ["]
    lines.extend(f"  {_json_literal(value)}," for value in values)
    lines.extend(["] as const;", ""])
    return lines


def _render_rpc_catalog(methods: Sequence[Mapping[str, Any]]) -> list[str]:
    lines = ["export const RPC_METHOD_SCOPES = {"]
    for item in methods:
        name = item.get("name")
        scope = item.get("required_scope")
        if isinstance(name, str) and isinstance(scope, str):
            lines.append(f"  {_json_literal(name)}: {_json_literal(scope)},")
    lines.extend(
        [
            "} as const;",
            "",
            "export type RpcMethod = keyof typeof RPC_METHOD_SCOPES;",
            "export type RpcScope = (typeof RPC_METHOD_SCOPES)[RpcMethod];",
            "",
        ]
    )
    return lines


def _coverage(
    *,
    manifest: Mapping[str, Any],
    rpc_methods: Mapping[str, Any],
    events: Mapping[str, Any],
    http_routes: Mapping[str, Any],
) -> dict[str, Any]:
    methods = rpc_methods.get("methods", [])
    observed_events = events.get("observed_client_events", [])
    routes = http_routes.get("routes", [])
    return {
        "contractDigest": manifest["digest"],
        "schemaVersion": manifest["schemaVersion"],
        "coverage": {
            "transportEnvelopes": "complete",
            "connectAndHello": "complete",
            "errorAndPolicyModels": "complete",
            "rpcCatalog": {
                "namesAndScopes": "complete",
                "payloadContracts": "deferred-by-domain",
                "totalMethods": len(methods) if isinstance(methods, list) else 0,
                "typedPayloadMethods": 0,
            },
            "events": {
                "envelope": "complete",
                "payloadContracts": "deferred-by-domain",
                "observedEvents": len(observed_events) if isinstance(observed_events, list) else 0,
                "typedPayloadEvents": 0,
            },
            "http": {
                "transportErrors": "complete",
                "payloadContracts": "deferred-by-domain",
                "totalRoutes": len(routes) if isinstance(routes, list) else 0,
                "typedRoutes": 0,
            },
        },
    }


def render_sdk_artifacts(
    *,
    contract_artifacts: Mapping[PurePosixPath, bytes] | None = None,
) -> dict[PurePosixPath, bytes]:
    """Render deterministic SDK types and machine-readable coverage."""

    artifacts = (
        dict(render_contract_artifacts())
        if contract_artifacts is None
        else dict(contract_artifacts)
    )
    protocol = json.loads(artifacts[PurePosixPath("protocol.schema.json")])
    rpc_methods = json.loads(artifacts[PurePosixPath("rpc-methods.json")])
    events = json.loads(artifacts[PurePosixPath("events.json")])
    http_routes = json.loads(artifacts[PurePosixPath("http-routes.json")])
    manifest = json.loads(artifacts[PurePosixPath("contract.json")])

    definitions = protocol.get("$defs", {})
    if not isinstance(definitions, Mapping):
        raise ValueError("protocol.schema.json must contain an object $defs")
    ordered_names = [
        "ErrorShape",
        "StateVersion",
        "ReqFrame",
        "ResFrame",
        "EventFrame",
        "PingFrame",
        "PongFrame",
        "ServerInfo",
        "FeaturesInfo",
        "SnapshotInfo",
        "PolicyInfo",
        "ContractInfo",
        "RuntimeInfo",
        "ProtocolRangeInfo",
        "ConnectParams",
        "HelloOk",
        "ClientFrame",
        "ServerFrame",
        "Frame",
    ]
    remaining = sorted(name for name in definitions if name not in ordered_names)

    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_client_contracts.py. Do not edit.",
        f"// Source contract: {manifest['digest']}",
        "",
        f"export const CLIENT_CONTRACT_SCHEMA_VERSION = {manifest['schemaVersion']} as const;",
        f"export const CLIENT_CONTRACT_DIGEST = {_json_literal(manifest['digest'])} as const;",
        "",
        "/** JSON Schema integer. Validate with Number.isInteger at runtime. */",
        "export type Integer = number;",
        "",
    ]
    for name in [*ordered_names, *remaining]:
        definition = definitions.get(name)
        if isinstance(name, str) and isinstance(definition, Mapping):
            lines.extend(_render_definition(name, definition))

    metadata = protocol.get("x-opensquilla-contract", {})
    canonical_connect = (
        metadata.get("connect", {}).get("canonical_client_frame", {})
        if isinstance(metadata, Mapping)
        else {}
    )
    if not isinstance(canonical_connect, Mapping):
        raise ValueError("protocol schema is missing canonical connect frame")
    lines.extend(
        [
            f"export type ConnectRequest = {_ts_type(canonical_connect)};",
            "",
        ]
    )

    error_codes = (
        metadata.get("errors", {}).get("declared_codes", [])
        if isinstance(metadata, Mapping)
        else []
    )
    if not isinstance(error_codes, list):
        error_codes = []
    lines.extend(_render_const_array("DECLARED_ERROR_CODES", error_codes))
    lines.append("export type DeclaredErrorCode = (typeof DECLARED_ERROR_CODES)[number];")
    lines.append("")

    methods = rpc_methods.get("methods", [])
    if not isinstance(methods, list):
        raise ValueError("rpc-methods.json must contain a methods array")
    lines.extend(_render_rpc_catalog(methods))

    declared_events = events.get("declared_events", [])
    observed_events = events.get("observed_client_events", [])
    event_patterns = events.get("event_patterns", [])
    for name, values in (
        ("DECLARED_EVENTS", declared_events),
        ("OBSERVED_CLIENT_EVENTS", observed_events),
        ("EVENT_PATTERNS", event_patterns),
    ):
        if not isinstance(values, list):
            raise ValueError(f"events.json {name} source must be an array")
        lines.extend(_render_const_array(name, values))
    lines.extend(
        [
            "export type DeclaredEvent = (typeof DECLARED_EVENTS)[number];",
            "export type ObservedClientEvent = (typeof OBSERVED_CLIENT_EVENTS)[number];",
            "export type EventPattern = (typeof EVENT_PATTERNS)[number];",
            "export type KnownEvent = DeclaredEvent | ObservedClientEvent;",
            "",
        ]
    )

    coverage = _coverage(
        manifest=manifest,
        rpc_methods=rpc_methods,
        events=events,
        http_routes=http_routes,
    )
    return {
        PurePosixPath("contract-coverage.json"): _json_bytes(coverage),
        PurePosixPath("src/generated.ts"): ("\n".join(lines).rstrip() + "\n").encode(),
    }


def check_sdk(
    sdk_root: Path,
    *,
    artifacts: Mapping[PurePosixPath, bytes] | None = None,
) -> GeneratedCheckResult:
    expected = render_sdk_artifacts() if artifacts is None else dict(artifacts)
    changed: list[PurePosixPath] = []
    missing: list[PurePosixPath] = []
    for relative_path in GENERATED_SDK_PATHS:
        target = sdk_root / relative_path.as_posix()
        if not target.is_file():
            missing.append(relative_path)
        elif target.read_bytes() != expected[relative_path]:
            changed.append(relative_path)
    return GeneratedCheckResult(changed=tuple(changed), missing=tuple(missing))


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with NamedTemporaryFile(
            mode="wb",
            prefix=f".{path.name}.",
            dir=path.parent,
            delete=False,
        ) as handle:
            handle.write(content)
            temporary = Path(handle.name)
        temporary.replace(path)
        os.chmod(path, 0o644)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def write_sdk(
    sdk_root: Path,
    *,
    artifacts: Mapping[PurePosixPath, bytes] | None = None,
) -> GeneratedCheckResult:
    expected = render_sdk_artifacts() if artifacts is None else dict(artifacts)
    for relative_path in GENERATED_SDK_PATHS:
        target = sdk_root / relative_path.as_posix()
        content = expected[relative_path]
        if not target.is_file() or target.read_bytes() != content:
            _atomic_write(target, content)
        else:
            os.chmod(target, 0o644)
    return check_sdk(sdk_root, artifacts=expected)


def check_identity(identity_path: Path, expected: bytes) -> GeneratedCheckResult:
    relative_path = PurePosixPath(identity_path.name)
    if not identity_path.is_file():
        return GeneratedCheckResult(missing=(relative_path,))
    if identity_path.read_bytes() != expected:
        return GeneratedCheckResult(changed=(relative_path,))
    return GeneratedCheckResult()


def write_identity(identity_path: Path, expected: bytes) -> GeneratedCheckResult:
    if not identity_path.is_file() or identity_path.read_bytes() != expected:
        _atomic_write(identity_path, expected)
    else:
        os.chmod(identity_path, 0o644)
    return check_identity(identity_path, expected)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated bytes")
    parser.add_argument("--contract-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--sdk-root", type=Path, default=DEFAULT_SDK_ROOT)
    parser.add_argument("--identity-path", type=Path, default=DEFAULT_IDENTITY_PATH)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    contract_artifacts = render_contract_artifacts()
    sdk_artifacts = render_sdk_artifacts(contract_artifacts=contract_artifacts)
    identity_artifact = render_contract_identity(
        json.loads(contract_artifacts[PurePosixPath("contract.json")])
    )
    contract_result = (
        check_contract(args.contract_dir, artifacts=contract_artifacts)
        if args.check
        else write_contract(args.contract_dir, artifacts=contract_artifacts)
    )
    sdk_result = (
        check_sdk(args.sdk_root, artifacts=sdk_artifacts)
        if args.check
        else write_sdk(args.sdk_root, artifacts=sdk_artifacts)
    )
    identity_result = (
        check_identity(args.identity_path, identity_artifact)
        if args.check
        else write_identity(args.identity_path, identity_artifact)
    )
    if contract_result.ok and sdk_result.ok and identity_result.ok:
        action = "matches" if args.check else "wrote"
        print(
            "Client contract, runtime identity, and TypeScript SDK "
            f"{action} generated sources"
        )
        return 0

    for category, paths in (
        ("contract changed", contract_result.changed),
        ("contract missing", contract_result.missing),
        ("contract unexpected", contract_result.unexpected),
        ("sdk changed", sdk_result.changed),
        ("sdk missing", sdk_result.missing),
        ("identity changed", identity_result.changed),
        ("identity missing", identity_result.missing),
    ):
        for path in paths:
            print(f"{category}: {path.as_posix()}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
